version: "3.8"

services: 
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=database
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database

networks:
  default:
    driver: bridge

volumes:
  pgdata:
    driver: local
    